site:
  title:   RHEL Lightspeed for RHEL Systems
  start_page: rcb-demo-test::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
